[project]
name = "grounded-sam-2"
version = "0.1.0"
description = "Adopted from https://github.com/IDEA-Research/Grounded-SAM-2"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "hydra-core>=1.3.2"
]

